export const colors = {
  primary: "#1677FF",
  primaryDark: "#0A5EDB",
  primaryLight: "#EAF3FF",
  primarySoft: "#F2F8FF",
  orange: "#FF8A00",
  orangeLight: "#FFF2E2",
  green: "#24C26A",
  greenLight: "#EAF9F0",
  purple: "#7B61FF",
  purpleLight: "#F1EFFF",
  red: "#FF4D4F",
  background: "#F6FAFF",
  backgroundAlt: "#F8FBFF",
  card: "#FFFFFF",
  cardSoft: "#F9FCFF",
  text: "#111827",
  textSecondary: "#4B5563",
  textMuted: "#8A94A6",
  border: "#E6EEF8",
  divider: "#EEF3FA",
  black: "#000000",
  white: "#FFFFFF"
} as const;
